---
title: "Analysis"
author: "Jessie Huang"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fiftystater)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

# Analysis

# Data Sources

```{r}
data_bmi <- read.csv('crc/bmi.csv', check.names = FALSE)
data_npo <- read.csv('crc/nutrition-physicalactivity-obesity.csv', check.names = FALSE)
```

```{r}
data('fifty_states')
colnames(fifty_states)[6] <- 'state_desc'
```

# Obesity

## Data Cleaning

```{r}
# EO-CRC rising in all races (especially White and Black) and males
risk_bmi_groups <- c('Obese (BMI 30.0 - 99.8)')
demographics <- c('18-24', '25-34', '35-44', '45-54', 'Black, non-Hispanic', 'White, non-Hispanic', 'American Indian or Alaskan Native, non-Hispanic', 'Asian, non-Hispanic', 'Native Hawaiian or other Pacific Islander, non-Hispanic', 'Multiracial, non-Hispanic', 'Other, non-Hispanic', 'Hispanic', 'Male')
race <- c('Black, non-Hispanic', 'White, non-Hispanic', 'American Indian or Alaskan Native, non-Hispanic', 'Asian, non-Hispanic', 'Native Hawaiian or other Pacific Islander, non-Hispanic', 'Multiracial, non-Hispanic', 'Other, non-Hispanic', 'Hispanic')
age <- c('18-24', '25-34', '35-44', '45-54')
sex <- c('Female', 'Male')
```

```{r}
data_bmi_clean <- data_bmi %>% 
  select(Year, Locationabbr, Locationdesc, Break_Out, Response, Data_value) %>%
  replace(is.na(.), 0)
head(data_bmi_clean)
```

```{r}
colnames(data_bmi_clean)[2] <- 'state_cd'
colnames(data_bmi_clean)[3] <- 'state_desc'
colnames(data_bmi_clean)[4] <- 'demographic'
colnames(data_bmi_clean)[5] <- 'BMI'
colnames(data_bmi_clean)[6] <- 'CrudePrevalence'

data_bmi_clean$CrudePrevalence <- ifelse(data_bmi_clean$CrudePrevalence!=0.0, data_bmi_clean$CrudePrevalence/100, 0)
data_bmi_clean$Year <- as.factor(data_bmi_clean$Year)
data_bmi_clean$state_cd <- as.factor(data_bmi_clean$state_cd)
data_bmi_clean$demographic <- as.factor(data_bmi_clean$demographic)
data_bmi_clean$BMI <- as.factor(data_bmi_clean$BMI)
data_bmi_clean$state_desc <- tolower(data_bmi_clean$state_desc)
```

```{r}
data_bmi_risk <- data_bmi_clean %>% 
  filter(demographic %in% demographics & BMI %in% risk_bmi_groups) %>%
  replace(is.na(.), 0)

data_bmi_age_risk <- data_bmi_clean %>% 
  filter(demographic %in% age & BMI %in% risk_bmi_groups)

data_bmi_sex_risk <- data_bmi_clean %>% 
  filter(demographic %in% sex & BMI %in% risk_bmi_groups)

data_bmi_race_risk <- data_bmi_clean %>% 
  filter(demographic %in% race & BMI %in% risk_bmi_groups)
```

## Age Model

```{r}
# finding demo's with a tendency toward obesity
# year by year all age groups report obese weight range by significant amount
# 45-54's in year 2021 was significant year of increase
mod.fit.age <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_age_risk)
summary(mod.fit.age)
plot(mod.fit.age)
```

## Sex Model

```{r}
# finding demo's with a tendency toward obesity
# year by year less males report obese weight range by significant amount than females, especially 2021 and 2022
mod.fit.sex <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_sex_risk)
summary(mod.fit.sex)
plot(mod.fit.sex)
```

## Race Model

### Year by Year
```{r}
# year by year 
# unclear, lot of missing data throughout the year of races, removing year for overall picture then. 
mod.fit.race <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_race_risk)
summary(mod.fit.race)
plot(mod.fit.race)
```

# Only Race
```{r}
# remove year for clearer picture
# american indian/alaskan native, black, hispanic, multiracial, and white increase in obesity weight range report by significant amount
# others are decrease (but i suspect it's from lack of data versus actual reporting)
mod.fit.race2 <- lm(CrudePrevalence ~ demographic, data=data_bmi_race_risk)
summary(mod.fit.race2)
plot(mod.fit.race2)
```

## Visualizations

```{r}
# filter to most recent year for most recent behavior
data_bmi_clean_2022 <- data_bmi_clean %>% 
  filter(Year==2022)
head(data_bmi_clean_2022)
```

```{r, warning=FALSE}
risk_demo <- c('American Indian or Alaskan Native, non-Hispanic', 'Black, non-Hispanic', 'Hispanic', 'Multiracial, non-Hispanic', 'White, non-Hispanic')
data_risk_demo <- data_bmi_clean_2022 %>%
    group_by(state_desc, demographic) %>%
    filter(demographic %in% risk_demo & BMI %in% risk_bmi_groups) %>%
    arrange(desc(CrudePrevalence))
head(data_risk_demo)

# joins
data_risk_demo_geo <- left_join(fifty_states,data_risk_demo, by='state_desc')
head(data_risk_demo_geo)
```

```{r, fig.height=6}
ggplot(data_risk_demo_geo, aes(x=reorder(state_desc, CrudePrevalence), y=CrudePrevalence, color=demographic)) +
  geom_point() +
  geom_segment(aes(x=state_desc, xend=state_desc, y=0, yend=CrudePrevalence)) +
  coord_flip() +
  theme_classic() +
  # ggtitle('Obesity Prevalence by Race and US State (2022)') + 
  labs(x = 'State', y = 'Crude Prevalence %', color='Demographic') 
```

# Nutrition

## Data Cleaning
Not much data, will have to go off who isn't eating daily fruits and vegetables....
```{r}
data_nutrition <- data_npo %>% filter(Class == 'Fruits and Vegetables')

data_nutrition_filtered <- data_nutrition %>% 
  select(YearEnd, LocationAbbr, LocationDesc,
         `Age(years)`,Gender,`Race/Ethnicity`,
         Question, Data_Value)
head(data_nutrition_filtered)
```


```{r}
colnames(data_nutrition_filtered)[1] <- 'Year'
colnames(data_nutrition_filtered)[2] <- 'state_cd'
colnames(data_nutrition_filtered)[3] <- 'state_desc'
colnames(data_nutrition_filtered)[4] <- 'age'
colnames(data_nutrition_filtered)[5] <- 'sex'
colnames(data_nutrition_filtered)[6] <- 'race_ethnicity'
colnames(data_nutrition_filtered)[7] <- 'diet_cat'
colnames(data_nutrition_filtered)[8] <- 'percent'

data_nutrition_filtered$state_desc <- tolower(data_nutrition_filtered$state_desc)
data_nutrition_filtered$Year <- as.factor(data_nutrition_filtered$Year)
data_nutrition_filtered$state_cd <- as.factor(data_nutrition_filtered$state_cd)
data_nutrition_filtered$state_desc <- as.factor(data_nutrition_filtered$state_desc)
data_nutrition_filtered$age <- as.factor(data_nutrition_filtered$age)
data_nutrition_filtered$sex <- as.factor(data_nutrition_filtered$sex)
data_nutrition_filtered$race_ethnicity <- as.factor(data_nutrition_filtered$race_ethnicity)
data_nutrition_filtered$diet_cat <- as.factor(data_nutrition_filtered$diet_cat)
data_nutrition_filtered$percent <- ifelse(data_nutrition_filtered$percent!=0.0, data_nutrition_filtered$percent/100, 0.0)

head(data_nutrition_filtered)
```

```{r}
age_levels <- c('18 - 24', '25 - 34', '35 - 44', '45 - 54')
sex_levels <- c('Female', 'Male')
race_levels <- c("2 or more races", "American Indian/Alaska Native", "Asian", "Hawaiian/Pacific Islander", "Hispanic", "Non-Hispanic Black", "Non-Hispanic White", "Other")

data_nutrition_age <- data_nutrition_filtered %>% 
  filter(age %in% age_levels)

data_nutrition_sex <- data_nutrition_filtered %>% 
  filter(sex %in% sex_levels)

data_nutrition_race <- data_nutrition_filtered %>% 
  filter(race_ethnicity %in% race_levels)
```

## Age Model

```{r}
# more younger not eating at least 1 fruit or 1 veg a day
mod.fit.nutrition.age <- lm(percent ~ age, data=data_nutrition_age)
summary(mod.fit.nutrition.age)
plot(mod.fit.nutrition.age)
```

## Sex Model

```{r}
# more male not eating at least 1 fruit or 1 veg a day
mod.fit.nutrition.sex <- lm(percent ~ sex, data=data_nutrition_sex)
summary(mod.fit.nutrition.sex)
plot(mod.fit.nutrition.sex)
```

## Race Model

```{r}
# less likely to respond to not eat at least 1 fruit or 1 veg a day: asian, white, other
# more likely to respond to not eat at least 1 fruit or 1 veg a day: 2 or more races, american indian or alaska native, hawaiian/pacific islander, hispanic, black
mod.fit.nutrition.race <- lm(percent ~ race_ethnicity, data=data_nutrition_race)
summary(mod.fit.nutrition.race)
plot(mod.fit.nutrition.race)
```

## Visualizations

```{r}
# 2019 most recent data for diet questions
data_nutrition_2019 <- data_nutrition_filtered %>% 
  filter(Year == 2019 & state_cd != 'US')

data_nutrition_geo_2019 <- left_join(fifty_states,data_nutrition_2019, by='state_desc')

data_nutrition_geo_age <- data_nutrition_geo_2019 %>%
  filter(age %in% age_levels)
data_nutrition_geo_sex <- data_nutrition_geo_2019 %>%
  filter(sex %in% sex_levels)
data_nutrition_geo_race <- data_nutrition_geo_2019 %>%
  filter(race_ethnicity %in% race_levels)
```

### Age

```{r}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_age, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_wrap(age~.)+
  theme_void() +
  labs(fill = 'Percent %')
```

### Sex

```{r, fig.width=5, fig.height=5}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_sex, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_grid(sex~.)+
  theme_void() +
  labs(fill = 'Percent %')
```

### Race

```{r}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_race, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_wrap(race_ethnicity~.)+
  theme_void() +
  labs(fill = 'Percent %')
```

# Fitness
