---
title: "BMITrend2"
author: "Jessie Huang"
date: "2024-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fiftystater)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
data_bmi <- read.csv('crc/bmi.csv', check.names = FALSE)
head(data_bmi)
```

```{r}
# EO-CRC rising in all races (especially White and Black) and males
risk_bmi_groups <- c('Obese (BMI 30.0 - 99.8)')
demographics <- c('18-24', '25-34', '35-44', '45-54', 'Black, non-Hispanic', 'White, non-Hispanic', 'American Indian or Alaskan Native, non-Hispanic', 'Asian, non-Hispanic', 'Native Hawaiian or other Pacific Islander, non-Hispanic', 'Multiracial, non-Hispanic', 'Other, non-Hispanic', 'Hispanic', 'Male')
race <- c('Black, non-Hispanic', 'White, non-Hispanic', 'American Indian or Alaskan Native, non-Hispanic', 'Asian, non-Hispanic', 'Native Hawaiian or other Pacific Islander, non-Hispanic', 'Multiracial, non-Hispanic', 'Other, non-Hispanic', 'Hispanic')
age <- c('18-24', '25-34', '35-44', '45-54')
sex <- c('Female', 'Male')
```

```{r}
data_bmi_clean <- data_bmi %>% 
  select(Year, Locationabbr, Locationdesc, Break_Out, Response, Data_value) %>%
  replace(is.na(.), 0)
head(data_bmi_clean)
```

```{r}
data("fifty_states")
colnames(fifty_states)[6] <- 'state_desc'
colnames(data_bmi_clean)[2] <- 'state_cd'
colnames(data_bmi_clean)[3] <- 'state_desc'
colnames(data_bmi_clean)[4] <- 'demographic'
colnames(data_bmi_clean)[5] <- 'BMI'
colnames(data_bmi_clean)[6] <- 'CrudePrevalence'

data_bmi_clean$CrudePrevalence <- ifelse(data_bmi_clean$CrudePrevalence!=0.0, data_bmi_clean$CrudePrevalence/100, 0)
data_bmi_clean$Year <- as.factor(data_bmi_clean$Year)
data_bmi_clean$state_cd <- as.factor(data_bmi_clean$state_cd)
data_bmi_clean$demographic <- as.factor(data_bmi_clean$demographic)
data_bmi_clean$BMI <- as.factor(data_bmi_clean$BMI)
data_bmi_clean$state_desc <- tolower(data_bmi_clean$state_desc)
```

```{r}
data_bmi_risk <- data_bmi_clean %>% 
  filter(demographic %in% demographics & BMI %in% risk_bmi_groups) %>%
  replace(is.na(.), 0)

data_bmi_age_risk <- data_bmi_clean %>% 
  filter(demographic %in% age & BMI %in% risk_bmi_groups)

data_bmi_sex_risk <- data_bmi_clean %>% 
  filter(demographic %in% sex & BMI %in% risk_bmi_groups)

data_bmi_race_risk <- data_bmi_clean %>% 
  filter(demographic %in% race & BMI %in% risk_bmi_groups)
```

```{r}
# finding demo's with a tendency toward obesity
# year by year all age groups report obese weight range by significant amount
# 45-54's in year 2021 was significant year of increase
mod.fit.age <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_age_risk)
summary(mod.fit.age)
plot(mod.fit.age)
```

```{r}
# finding demo's with a tendency toward obesity
# year by year less males report obese weight range by significant amount than females, especially 2021 and 2022
mod.fit.sex <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_sex_risk)
summary(mod.fit.sex)
plot(mod.fit.sex)
```


```{r}
# year by year 
# unclear, lot of missing data throughout the year of races, removing year for overall picture then. 
mod.fit.race <- lm(CrudePrevalence ~ Year + demographic + Year*demographic, data=data_bmi_race_risk)
summary(mod.fit.race)
plot(mod.fit.race)

# remove year for clearer picture
# american indian/alaskan native, black, hispanic, multiracial, and white increase in obesity weight range report by significant amount
# others are decrease (but i suspect it's from lack of data versus actual reporting)
mod.fit.race2 <- lm(CrudePrevalence ~ demographic, data=data_bmi_race_risk)
summary(mod.fit.race2)
plot(mod.fit.race2)
```

# visualize findings

```{r}
# filter to most recent year for most recent behavior
data_bmi_clean_2022 <- data_bmi_clean %>% 
  filter(Year==2022)
data_bmi_clean_2022
```

```{r, warning=FALSE}
risk_demo <- c('American Indian or Alaskan Native, non-Hispanic', 'Black, non-Hispanic', 'Hispanic', 'Multiracial, non-Hispanic', 'White, non-Hispanic')
data_risk_demo <- data_bmi_clean_2022 %>%
    group_by(state_desc, demographic) %>%
    filter(demographic %in% risk_demo & BMI %in% risk_bmi_groups) %>%
    arrange(desc(CrudePrevalence))
head(data_risk_demo)

# joins
data_risk_demo_geo <- left_join(fifty_states,data_risk_demo, by='state_desc')
head(data_risk_demo_geo)
```

Summary:
Year: 2022
Significant races: American Indian or Alaskan Native, non-Hispanic, Black, non-Hispanic, Hispanic, Multiracial, non-Hispanic, White, non-Hispanic


```{r}
# finding top 10 states for high risk demographics
data_bmi_clean %>% 
  filter(Year == 2022 & 
           demographic %in% race, 
           BMI == 'Obese (BMI 30.0 - 99.8)') %>%
  arrange(desc(CrudePrevalence))
data_risk_demo_geo
```

```{r, fig.height=8}
ggplot(data_risk_demo_geo, aes(x=state_desc, y=CrudePrevalence, color=demographic)) +
  geom_point() +
  geom_segment(aes(x=state_desc, xend=state_desc, y=0, yend=CrudePrevalence)) +
  coord_flip() +
  theme_classic() +
  ggtitle('Obesity Prevalence by Race and US State (2022)') + 
  labs(x = 'State', y = 'Crude Prevalence %', color='Demographic')
```

