---
title: "Analysis"
author: "Jessie Huang"
date: "2024-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(ggplot2)
```

```{r}
data <- read.csv('crc/colorectal_cancer_table_final.csv', check.names = FALSE)
head(data)
```

```{r}
age_group <- as.factor(data$`Age recode with <1 year olds`)
sex <- as.factor(data$Sex)
race_ethnicity <- as.factor(data$`Race/ethnicity`)
year <- as.integer(data$`Year of diagnosis`)

data$age_group <- age_group
data$sex <- sex
data$race_ethnicity <- race_ethnicity
data$year <- year
head(data)
```


```{r}
# filter out elder age groups
elderlies <- c('50-54 years', '55-59 years', '60-64 years', '65-69 years', '70-74 years', '75-79 years', '80-84 years', '85+ years')
df_filtered <- data %>% 
  filter(! age_group %in% elderlies) %>%
  select(year, `Patient ID`, age_group, sex, race_ethnicity)
df_filtered
```

```{r}
df_counts <- df_filtered %>% 
  group_by(year,age_group,sex,race_ethnicity, .drop = FALSE) %>%
  count(name= 'Dx Counts', sort=TRUE)
df_counts
```

```{r}
hist(df_counts$`Dx Counts`)
ggplot(df_counts, aes(x = `Dx Counts`)) +
    geom_bar()
```

```{r}
model.fit <- lm(`Dx Counts`~ age_group+sex+race_ethnicity, data=df_counts)
summary(model.fit)
```
```{r}
model.fit2 <- lm(`Dx Counts`~age_group+sex+race_ethnicity+
                   age_group*sex+age_group*race_ethnicity+sex*race_ethnicity, data=df_counts)
print(summary(model.fit2))
```

```{r}
model.fit3 <- lm(`Dx Counts`~age_group+sex+race_ethnicity+
                   age_group*sex+age_group*race_ethnicity+sex*race_ethnicity+
                   age_group*sex*race_ethnicity, data=df_counts)
print(summary(model.fit3))
```

```{r}
risk_states <- c('OK', 'AL', 'VA', 'SD', 'WI', 'ME', 'WY', 'MS', 'WV', 'IN')
data_risk_states <- data_risk_demo_geo %>%
  filter(state_cd %in% risk_states) %>%
  arrange(desc(CrudePrevalence))
head(data_risk_states)
```

```{r}
# black obesity prevalence > white obesity prevalence
# asian is low obesity prevalence compared to other races besides significant increase shown in model

data_risk_states_filter <- data_risk_states %>% filter(! demographic %in% c('Asian, non-Hispanic', 'White, non-Hispanic'))
p <- ggplot() + 
  geom_polygon(data = data_risk_demo_geo, aes(x=long, y=lat, group = group, fill=CrudePrevalence)) +
  scale_size(name="", range = c(2, 5)) +
  theme_void() +
  ggtitle('Obesity Prevalence of High Risk Races in the US (2022)') + 
  labs(fill = c('Crude Prevalence %'), color=c('Demographic of Highest Prevalence'))
p + geom_polygon(data = data_risk_states_filter, aes(x=long, y=lat, group = group, fill=CrudePrevalence, color=demographic), size=1)
```

