---
title: "Nutrition"
author: "Jessie Huang"
date: "2024-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fiftystater)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

# Nutrition
Not much data, will have to go off who isn't eating fruits and vegetables
```{r}
data_npo <- read.csv('crc/nutrition-physicalactivity-obesity.csv', check.names = FALSE)

data_nutrition <- data_npo %>% filter(Class == 'Fruits and Vegetables')

data_nutrition_filtered <- data_nutrition %>% select(YearEnd, LocationAbbr, LocationDesc,
                                                     `Age(years)`,Gender,`Race/Ethnicity`, 
                                                     Question, Data_Value)
head(data_nutrition_filtered)
```
```{r}

```

```{r}
colnames(data_nutrition_filtered)[1] <- 'Year'
colnames(data_nutrition_filtered)[2] <- 'state_cd'
colnames(data_nutrition_filtered)[3] <- 'state_desc'
colnames(data_nutrition_filtered)[4] <- 'age'
colnames(data_nutrition_filtered)[5] <- 'sex'
colnames(data_nutrition_filtered)[6] <- 'race_ethnicity'
colnames(data_nutrition_filtered)[7] <- 'diet_cat'
colnames(data_nutrition_filtered)[8] <- 'percent'

data_nutrition_filtered$state_desc <- tolower(data_nutrition_filtered$state_desc)
data_nutrition_filtered$Year <- as.factor(data_nutrition_filtered$Year)
data_nutrition_filtered$state_cd <- as.factor(data_nutrition_filtered$state_cd)
data_nutrition_filtered$state_desc <- as.factor(data_nutrition_filtered$state_desc)
data_nutrition_filtered$age <- as.factor(data_nutrition_filtered$age)
data_nutrition_filtered$sex <- as.factor(data_nutrition_filtered$sex)
data_nutrition_filtered$race_ethnicity <- as.factor(data_nutrition_filtered$race_ethnicity)
data_nutrition_filtered$diet_cat <- as.factor(data_nutrition_filtered$diet_cat)
data_nutrition_filtered$percent <- ifelse(data_nutrition_filtered$percent!=0.0, data_nutrition_filtered$percent/100, 0.0)

head(data_nutrition_filtered)
```



# modeling

```{r}
age_levels <- c('18 - 24', '25 - 34', '35 - 44', '45 - 54')
sex_levels <- c('Female', 'Male')
race_levels <- c("2 or more races", "American Indian/Alaska Native", "Asian", "Hawaiian/Pacific Islander", "Hispanic", "Non-Hispanic Black", "Non-Hispanic White", "Other")

data_nutrition_age <- data_nutrition_filtered %>% 
  filter(age %in% age_levels)

data_nutrition_sex <- data_nutrition_filtered %>% 
  filter(sex %in% sex_levels)

data_nutrition_race <- data_nutrition_filtered %>% 
  filter(race_ethnicity %in% race_levels)
```

# age
```{r}
# more younger not eating at least 1 fruit or 1 veg a day
mod.fit.diet.age <- lm(percent ~ age, data=data_nutrition_age)
summary(mod.fit.diet.age)
plot(mod.fit.inactive.age)
```

# sex
```{r}
# more male not eating at least 1 fruit or 1 veg a day
mod.fit.diet.sex <- lm(percent ~ sex, data=data_nutrition_sex)
summary(mod.fit.diet.sex)
plot(mod.fit.inactive.sex)
```
# race
```{r}
# less likely to respond to not eat at least 1 fruit or 1 veg a day: asian, white, other
# more likely to respond to not eat at least 1 fruit or 1 veg a day: 2 or more races, american indian or alaska native, hawaiian/pacific islander, hispanic, black
mod.fit.diet.race <- lm(percent ~ race_ethnicity, data=data_nutrition_race)
summary(mod.fit.diet.race)
plot(mod.fit.diet.race)
```


# visualize

```{r}
# 2019 most recent data for diet questions
data_nutrition_2019 <- data_nutrition_filtered %>% 
  filter(Year == 2019 & state_cd != 'US')
head(data_nutrition_2019)

data_nutrition_geo_2019 <- left_join(fifty_states,data_nutrition_2019, by='state_desc')
```
# age

```{r}
data_nutrition_geo_age <- data_nutrition_geo_2019 %>%
  filter(age %in% age_levels)
```

```{r}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_age, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_wrap(age~.)+
  theme_void() +
  # ggtitle('Inactive Adults - Race') + 
  labs(fill = 'Percent %')
```

# sex

```{r}
data_nutrition_geo_sex <- data_nutrition_geo_2019 %>%
  filter(sex %in% sex_levels)
```

```{r, fig.width=5, fig.height=5}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_sex, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_grid(sex~.)+
  theme_void() +
  # ggtitle('Inactive Adults - Race') + 
  labs(fill = 'Percent %')
```

# race

```{r}
data_nutrition_geo_race <- data_nutrition_geo_2019 %>%
  filter(race_ethnicity %in% race_levels)
```

```{r}
ggplot() + 
  geom_polygon(data=data_nutrition_geo_race, aes(x=long, y=lat, group = group, fill=percent), color='white') +
  scale_size(name="") + 
  facet_wrap(race_ethnicity~.)+
  theme_void() +
  # ggtitle('Inactive Adults - Race') + 
  labs(fill = 'Percent %')
```

